import articles from '../content/articles.json';

/**
 * articles.json is generated by scripts/build-articles.ts from the Markdown in
 * content/articles/. Run `pnpm articles` after adding or editing one; do not
 * edit the JSON by hand.
 */
const Writing = () => {
  if (articles.length === 0) return null;

  return <section id="writing" className="section-padding bg-black text-white">
      <div className="container mx-auto">
        <h2 className="text-4xl md:text-5xl font-light mb-4 text-center">
          Writing
        </h2>
        <p className="text-lg font-light text-center text-gray-400 mb-12 max-w-2xl mx-auto">
          Longer pieces, written up properly rather than left as notes.
        </p>

        <div className="max-w-4xl mx-auto space-y-8">
          {articles.map(article => <article key={article.slug} className="border-t border-white pt-8">
              <a href={article.url} className="group block">
                <p className="text-sm font-light text-gray-400 font-grotesk tracking-wider mb-3">
                  {article.displayDate} · {article.readingMinutes} min read
                </p>
                <h3 className="text-2xl md:text-3xl font-medium mb-4 group-hover:underline">
                  {article.title}
                </h3>
                <p className="text-lg font-light leading-relaxed text-gray-300 mb-4">
                  {article.description}
                </p>
                <ul className="flex flex-wrap gap-2 mb-4">
                  {article.tags.map(tag => <li key={tag} className="border border-gray-600 px-3 py-1 text-sm font-light text-gray-400">
                      {tag}
                    </li>)}
                </ul>
                <span className="inline-block border px-4 py-1.5 text-sm font-light tracking-wider font-grotesk group-hover:bg-white group-hover:text-black transition">
                  Read the article
                </span>
              </a>
            </article>)}
        </div>
      </div>
    </section>;
};
export default Writing;
