/**
 * public/sitemap.xml, written by build-articles.ts because that is the script
 * that knows the article list. Pages that exist in both languages list each
 * other as xhtml:link alternates, each including itself, plus x-default
 * pointing at the English page, which is the form search engines expect.
 */
export type Alternate = { hreflang: string; href: string };

export type SitemapEntry = {
  loc: string;
  lastmod?: string;
  changefreq: 'monthly' | 'yearly';
  priority: string;
  alternates?: Alternate[];
};

const escapeXml = (s: string): string => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

export function buildSitemap(entries: SitemapEntry[]): string {
  const urls = entries.map(e =>
    [
      '  <url>',
      `    <loc>${escapeXml(e.loc)}</loc>`,
      ...(e.alternates ?? []).map(
        a => `    <xhtml:link rel="alternate" hreflang="${a.hreflang}" href="${escapeXml(a.href)}"/>`,
      ),
      ...(e.lastmod ? [`    <lastmod>${e.lastmod}</lastmod>`] : []),
      `    <changefreq>${e.changefreq}</changefreq>`,
      `    <priority>${e.priority}</priority>`,
      '  </url>',
    ].join('\n'),
  );
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/build-articles.ts. Do not hand-edit; run pnpm articles. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n');
}

/** One entry per URL of a translated pair, each listing both plus x-default. */
export function pair(
  en: string,
  de: string,
  rest: Omit<SitemapEntry, 'loc' | 'alternates'>,
): SitemapEntry[] {
  const alternates: Alternate[] = [
    { hreflang: 'en-GB', href: en },
    { hreflang: 'de-DE', href: de },
    { hreflang: 'x-default', href: en },
  ];
  return [
    { loc: en, alternates, ...rest },
    { loc: de, alternates, ...rest },
  ];
}
